name: gdgikorodu
description: A new Flutter application.

version: 0.0.2+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  cached_network_image: ^2.0.0
  url_launcher: ^5.4.1
  flutter_webview_plugin: ^0.3.10+1
  share: ^0.6.3+5

dev_dependencies:
  flutter_test:
    sdk: flutter


# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/images/gdg-logo.jpg
  - assets/images/gdg-ikorodu.jpg
  #  - images/a_dot_ham.jpeg

  # example:
  # fonts:
  #   - family: Schyler
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
